language: node_js

node_js:
  - "6"

# before_install:
#   - export CHROME_BIN=chromium-browser
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
#
# addons:
#   apt:
#     packages:
#       - xvfb
#
# install:
#   - "export DISPLAY=':99.0'"
#   - "Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &"

before_install:
	- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

script:
  - "npm test"
