language: node_js
node_js:
  - "6"
before_install:
  # Use X Virtual Frame Buffer
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1027x768x16"
  - sleep 3 # give xvfb some time to start
  - "export DISPLAY=:99.0"
  # - yarn install
script:
  - "HOST=prod npm test"
